openapi: 3.1.0
info:
  version: 1.0.0
  title: <contacts>
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: <documentation of contacts app>
tags:
  # теги, що ви будете використовувати
servers:
  - url: <http://localhost:3000>
  - url: <https://example.com/api/v1>
paths:
  # тут будуть посилання на ендпоінти
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
