name: Sync README to All Branches

on:
  push:
    branches:
      - main
    paths:
      - 'README.md'

jobs:
  sync-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Fetch all branches
        run: git fetch --all --prune

      - name: Sync README.md to other branches
        run: |
          for remote_branch in $(git branch -r | grep -vE 'origin/(main|HEAD)$'); do
            branch_name=${remote_branch#origin/}
            echo "🔁 Syncing README to branch: $branch_name"

            git checkout -B "$branch_name" "$remote_branch"
            git checkout main -- README.md

            if ! git diff --quiet; then
              git commit -m "Sync README from main [automated]"
              git push origin "$branch_name"
              echo "✅ README updated in $branch_name"
            else
              echo "ℹ️ No changes needed in $branch_name"
            fi
          done
