name: Sync README to All Branches

on:
  push:
    branches:
      - main
    paths:
      - "README.md"

jobs:
  sync-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Important for full branch access
          ref: main

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Fetch all branches
        run: git fetch --all

      - name: Sync README to other branches
        run: |
          for branch in $(git for-each-ref --format='%(refname:short)' refs/remotes/origin/ | grep -v '^origin/main$' | grep -v '^origin/HEAD$'); do
            local_branch=$(echo $branch | sed 's|origin/||')
            echo "🔁 Syncing README to branch: $local_branch"

            git checkout -B $local_branch origin/$local_branch
            git checkout main -- README.md

            if ! git diff --quiet; then
              git commit -m "Sync README from main [automated]"
              git push origin $local_branch
              echo "✅ README updated in $local_branch"
            else
              echo "ℹ️ No README changes needed in $local_branch"
            fi
          done

      - name: Switch back to main
        run: git checkout main
