name: Sync README to All Branches

on:
  push:
    branches:
      - main
    paths:
      - "README.md"

jobs:
  sync-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Sync README to all other branches
        run: |
          git fetch --all
          branches=$(git branch -r | grep -vE 'main|HEAD' | sed 's/origin\///')

          for branch in $branches; do
            echo "Processing branch: $branch"

            git checkout $branch
            git checkout main -- README.md

            if ! git diff --quiet; then
              git commit -am "Sync README from main [auto]"
              git push origin $branch
              echo "✅ Updated README in $branch"
            else
              echo "ℹ️ No changes to README in $branch"
            fi
          done
